version: '3.8'

services:
  # Spring Boot Application
  my-spring-app:
    image: restapicalculator
    ports:
      - "8080:8080"  # Adjust the port if needed
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/calci_request?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1*SecurityPassword
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_TYPE: redis
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 1h

  # MySQL Database
  mysql:
    image: mysql:8.2.0
    ports:
      - "3307:3306"  # Mapping container port 3306 to host port 3307
    environment:
      MYSQL_DATABASE: calci_request
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1*SecurityPassword
      MYSQL_ROOT_PASSWORD: 1*SecurityPassword

  # Redis Server
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Mapping container port 6379 to host port 6379
